[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
viaIR = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "./out/"}, { access = "read", path = "./mc.toml" }, { access = "read", path = "./lib/mc/mc.toml" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
  '@mc/=lib/mc/'
]